#!/bin/bash

# Install awsudo on Strider.

set -e

venv="/usr/local/awsudo"

if [[ "$STRIDER_REPO_DOMAIN" == 'master.paperg.awsudo' ]]; then
    [[ ! -d "$venv" ]] && sudo virtualenv "$venv"
    sudo "${venv}/bin/pip" install --upgrade .
    [[ ! -e /usr/local/bin/awsudo ]] && sudo ln -s "${venv}/bin/awsudo" /usr/local/bin/awsudo
    [[ ! -e /usr/local/bin/awsrotate ]] && sudo ln -s "${venv}/bin/awsrotate" /usr/local/bin/awsrotate
    exit 0
fi
